apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: microservices
spec:
  selector:
    app: zipkin
  type: ClusterIP
  ports:
    - name: zipkin-port
      port: 9411
      protocol: TCP
      targetPort: 9411
  sessionAffinity: None
